// Real Chromium interaction test. npm install --no-save playwright; npx playwright install chromium
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),zlib=require('node:zlib');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'../web'),out=path.resolve(__dirname,'../.local/browser');
fs.mkdirSync(out,{recursive:true});
// Decode Chromium PNG screenshots to prove that the unobstructed canvas has rendered lines.
function colours(png){
 let p=8,w,h,bpp,parts=[];
 while(p<png.length){const n=png.readUInt32BE(p),type=png.toString('ascii',p+4,p+8),data=png.subarray(p+8,p+8+n);p+=n+12;
  if(type==='IHDR'){w=data.readUInt32BE(0);h=data.readUInt32BE(4);assert.equal(data[8],8);bpp=data[9]===6?4:data[9]===2?3:0;assert.ok(bpp);}
  if(type==='IDAT')parts.push(data);
 }
 const raw=zlib.inflateSync(Buffer.concat(parts)),stride=w*bpp,values=new Set();let previous=Buffer.alloc(stride),offset=0;
 for(let y=0;y<h;y++){const filter=raw[offset++],row=Buffer.alloc(stride);for(let x=0;x<stride;x++){
  const a=x>=bpp?row[x-bpp]:0,b=previous[x],c=x>=bpp?previous[x-bpp]:0,q=a+b-c;
  const pa=Math.abs(q-a),pb=Math.abs(q-b),pc=Math.abs(q-c),prediction=filter===0?0:filter===1?a:filter===2?b:filter===3?Math.floor((a+b)/2):pa<=pb&&pa<=pc?a:pb<=pc?b:c;
  row[x]=(raw[offset++]+prediction)&255;
 }for(let x=0;x<stride;x+=bpp)values.add(`${row[x]},${row[x+1]},${row[x+2]}`);previous=row;}
 return values.size;
}
const server=http.createServer((req,res)=>{try{const name=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=path.resolve(root,'.'+(name==='/'?'/index.html':name));if(!file.startsWith(root+path.sep))throw Error('Path outside web');const data=fs.readFileSync(file);res.setHeader('Content-Type',({'.html':'text/html','.mjs':'text/javascript','.css':'text/css','.json':'application/json'})[path.extname(file)]||'application/octet-stream');res.end(data);}catch{res.statusCode=404;res.end('Not found');}});
(async()=>{let browser;const report={checks:[],errors:[]};try{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 browser=await chromium.launch({...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{}),headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const page=await browser.newPage({viewport:{width:1280,height:900},acceptDownloads:true});
 page.on('pageerror',e=>report.errors.push(e.message));
 await page.goto(`http://127.0.0.1:${server.address().port}/?baseline`,{waitUntil:'networkidle'});
 await page.waitForFunction(()=>window.electricalExplorer?.state.vertexCount>0);
 assert.equal(await page.locator('#error').textContent(),'');
 const playCases=[];const state=async()=>{const value=await page.evaluate(()=>window.electricalExplorer.state);if(value.routes.length>=48&&playCases.length<12){playCases.push({id:'case-'+String(playCases.length+1).padStart(2,'0'),settings:value.settings,routes:value.routes.map((r,i)=>({id:'route-'+(i+1),length:r.length,points:r.points}))});const folder=path.resolve(__dirname,'../.local/play-audit');fs.mkdirSync(folder,{recursive:true});fs.writeFileSync(path.join(folder,'cases.tmp'),JSON.stringify({cases:playCases}));fs.renameSync(path.join(folder,'cases.tmp'),path.join(folder,'cases.json'));}return value;};
 const clip={x:350,y:0,width:930,height:790};
 const initial=await page.screenshot({path:path.join(out,'initial.png'),clip});
 report.canvasColours=colours(initial);assert.ok(report.canvasColours>10,'Canvas must contain rendered geometry');report.checks.push('nonempty WebGL canvas');
 await page.locator('[name=height]').fill('2.5');await page.getByRole('button',{name:'Apply geometry',exact:true}).click();assert.equal((await state()).settings.height,2.5);report.checks.push('numeric geometry applied');
 for(const mode of ['walk','fly']){await page.locator('#mode').selectOption(mode);await page.locator('#scene').focus();const before=await page.screenshot({clip});await page.keyboard.down('w');await page.waitForTimeout(400);await page.keyboard.up('w');const after=await page.screenshot({clip});assert.equal((await state()).mode,mode);assert.ok(!before.equals(after),`${mode} W changes rendered view`);report.checks.push(`${mode} movement`);}
 await page.locator('#start').click();await page.keyboard.down('w');await page.waitForTimeout(400);await page.keyboard.up('w');const forward=(await state()).distance;assert.ok(forward>0);await page.keyboard.down('s');await page.waitForTimeout(180);await page.keyboard.up('s');assert.ok((await state()).distance<forward);report.checks.push('cable W/S distance');
 await page.locator('#blueprint').click();assert.equal((await state()).mode,'top');assert.equal(await page.locator('aside').isVisible(),false);await page.locator('#show').click();assert.equal(await page.locator('aside').isVisible(),true);await page.locator('#hide').click();assert.equal(await page.locator('aside').isVisible(),false);assert.equal(await page.evaluate(()=>document.activeElement.id),'scene');await page.locator('#show').click();report.checks.push('blueprint and controls');
 await page.locator('summary').filter({hasText:'Cable route files'}).click();
 const routes=[{id:'browser-test',label:'Browser metric test',points:[[0,0,0],[3,4,0],[3,4,12]]}],envelope={schema:'electrical-routes/1',units:'metres',axes:'ENU',routes};
 await page.locator('#route-file').setInputFiles({name:'routes.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(envelope))});await page.waitForFunction(()=>window.electricalExplorer.state.routes[0].id==='browser-test');assert.equal((await state()).routes[0].length,17);
 const downloadPromise=page.waitForEvent('download');await page.locator('#export-routes').click();const download=await downloadPromise;await download.saveAs(path.join(out,'exported-routes.json'));assert.deepEqual(JSON.parse(fs.readFileSync(path.join(out,'exported-routes.json'),'utf8')).routes,routes);report.checks.push('real file import/export and 17 m length');
 await page.locator('#plantPreset').click();assert.equal((await state()).mode,'top');const inventory=await page.evaluate(()=>electricalExplorer.plantInventory);assert.equal(inventory.stationCount,10);await page.screenshot({path:path.join(out,'plant.png')});report.checks.push('100 MWp overview button');await page.locator('#show').click();await page.locator('#arrayNumber').fill('100');await page.locator('#focusArray').click();assert.equal((await state()).mode,'fly');assert.equal(await page.evaluate(()=>document.activeElement.id),'scene');assert.equal(await page.locator('#error').textContent(),'');report.checks.push('plant array focus');
 await page.screenshot({path:path.join(out,'final.png')});
 await page.goto(`http://127.0.0.1:${server.address().port}/`,{waitUntil:'networkidle'});
 await page.waitForFunction(()=>electricalExplorer.acInventory()?.phaseCables===84);assert.equal((await state()).mode,'orbit');assert.equal(await page.locator('aside').isVisible(),false);await page.screenshot({path:path.join(out,'ac-trench-default.png')});await page.locator('#direct-top').click();const acTarget=await page.evaluate(()=>electricalExplorer.project(electricalExplorer.getPickTargets()[0].point));await page.mouse.click(acTarget[0],acTarget[1]);await page.locator('#ac-depth').fill('2');await page.locator('#ac-depth').press('Tab');assert.equal(await page.evaluate(()=>electricalExplorer.getTrench().depth),2);await page.locator('#ac-formation').click();assert.equal(await page.evaluate(()=>electricalExplorer.getTrench().formation),'flat');const acLength=(await state()).routes[0].length;await page.locator('#ac-move').click();await page.mouse.move(500,350);await page.mouse.down();await page.mouse.move(540,350);await page.mouse.up();assert.notEqual((await state()).routes[0].length,acLength);report.checks.push('AC trench default:28inverters84cables2transformers;depth2m;flat;equipmentdrag updatesroute');await page.evaluate(()=>electricalExplorer.setACSectionCount(0,16));assert.equal((await state()).routes.length,90);await page.evaluate(()=>electricalExplorer.setACSectionCount(0,12));assert.equal((await state()).routes.length,78);await page.evaluate(()=>electricalExplorer.setACSectionCount(0,14));report.checks.push('AC inverter additions/subtractions update three cables per inverter');await page.locator('#direct-dc').click();await page.waitForFunction(()=>electricalExplorer.blockInventory()?.strings===24);
 const inv=await page.evaluate(()=>electricalExplorer.blockInventory());assert.equal(inv.modulesPerString,30);assert.ok((await page.locator('#string-stc').textContent()).includes('1377.0 V'));assert.ok((await page.locator('#string-stc').textContent()).includes('1143.0 V'));assert.equal(inv.modules,900);assert.equal(inv.totalStrings,30);assert.equal(inv.spareStrings,6);assert.equal(inv.connectedModules,720);assert.equal(inv.dcHomeCables,48);assert.equal(inv.seriesLinks,696);assert.equal((await state()).mode,'orbit');assert.equal(await page.locator('aside').isVisible(),false);
 await page.screenshot({path:path.join(out,'full-table-3d.png')});const projected=await page.evaluate(()=>electricalExplorer.project([10,30,2]));await page.mouse.move(600,400);await page.mouse.wheel(0,-250);await page.waitForTimeout(120);const zoomed=await page.evaluate(()=>electricalExplorer.project([10,30,2]));assert.notDeepEqual(zoomed,projected);const frameA=await page.locator('#scene').screenshot();await page.waitForTimeout(300);const frameB=await page.locator('#scene').screenshot();assert.notDeepEqual(frameA,frameB);assert.equal(await page.evaluate(()=>document.getElementById('scene').getContext('webgl').getError()),0);report.checks.push('full paired900-module table; mouse wheel zoom; animated flow changes actual canvas; no WebGL errors');await page.locator('#direct-top').click();const target=await page.evaluate(()=>electricalExplorer.project(electricalExplorer.getPickTargets()[0].point));await page.mouse.click(target[0],target[1]);await page.waitForSelector('#direct-height');await page.locator('#direct-height').fill('4');await page.locator('#direct-ridge').fill('1');await page.locator('#direct-apply').click();assert.equal((await state()).settings.height,4);assert.equal(await page.evaluate(()=>electricalExplorer.getRidgeGap()),1);assert.equal((await state()).routes.length,48);await page.screenshot({path:path.join(out,'complete-inverter-block.png')});report.checks.push('default 30-series /24-string /48-cable block; angled view by default; direct click edits height');await page.locator('#direct-gap').fill('12');await page.locator('#direct-apply').click();assert.equal(await page.evaluate(()=>electricalExplorer.getSpacing()),12);await page.locator('#direct-move').click();const oldPoint=await page.evaluate(()=>electricalExplorer.getPickTargets()[0].point);await page.mouse.move(500,350);await page.mouse.down();await page.mouse.move(540,350);await page.mouse.up();const movedPoint=await page.evaluate(()=>electricalExplorer.getPickTargets()[0].point);assert.ok(movedPoint[0]>oldPoint[0]);await page.locator('#place-table').click();await page.mouse.click(950,500);assert.equal(await page.evaluate(()=>electricalExplorer.blockInventory().strings),48);assert.equal((await state()).routes.length,96);report.checks.push('row gap, mouse table movement, click placement adds a complete900-module paired table;24connected strings/48cables');const cableBefore=(await state()).routes[0].length;const inverterTarget=await page.evaluate(()=>electricalExplorer.project(electricalExplorer.getPickTargets().find(t=>t.kind==='inverter').point));await page.mouse.click(inverterTarget[0],inverterTarget[1]);await page.locator('#move-inverter').click();await page.mouse.move(800,350);await page.mouse.down();await page.mouse.move(850,350);await page.mouse.up();assert.notEqual((await state()).routes[0].length,cableBefore);report.checks.push('inverter drag recalculates connected cable lengths');
 await page.locator('#direct-station').click();await page.waitForFunction(()=>electricalExplorer.stationInventory()?.tables===23);const station=await page.evaluate(()=>electricalExplorer.stationInventory());assert.equal(station.installedModules,20700);assert.equal(station.connectedModules,20160);assert.equal(station.connectedStrings,672);assert.equal(station.spareStrings,18);assert.deepEqual(station.stringsPerInverter,Array(28).fill(24));assert.equal(station.dcHomeCables,1344);assert.equal(station.acPhaseCables,84);assert.equal((await state()).routes.length,1428);assert.equal(station.transformers,2);await page.screenshot({path:path.join(out,'full-station.png')});await page.locator('#direct-top').click();const beforeStationMove=(await state()).routes[0].length;await page.evaluate(()=>electricalExplorer.moveInverter(15,0,1));assert.notEqual((await state()).routes[0].length,beforeStationMove);await page.locator('#place-table').click();await page.mouse.click(800,600);assert.equal(await page.evaluate(()=>electricalExplorer.stationInventory().tables),24);assert.equal(await page.evaluate(()=>electricalExplorer.stationInventory().spareStrings),48);assert.equal((await state()).routes.length,1428);assert.equal(await page.evaluate(()=>document.getElementById('scene').getContext('webgl').getError()),0);report.checks.push('complete station:23tables,672strings,28inverters,1344DC+84AC,2transformers; move inverter and add table without overconnecting');await page.locator('#direct-dc').click();assert.equal(await page.evaluate(()=>electricalExplorer.blockInventory().modules),900);
 const mobileContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const mobile=await mobileContext.newPage();mobile.on('pageerror',e=>report.errors.push(e.message));await mobile.goto(`http://127.0.0.1:${server.address().port}/`,{waitUntil:'networkidle'});await mobile.waitForFunction(()=>electricalExplorer.acInventory()?.phaseCables===84);assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.locator('[data-view="walk"]').tap();await mobile.locator('#direct-dc').tap();await mobile.locator('#direct-top').tap();await mobile.locator('#place-table').tap();await mobile.touchscreen.tap(190,450);assert.equal(await mobile.evaluate(()=>electricalExplorer.blockInventory().strings),48);await mobile.screenshot({path:path.join(out,'mobile-touch.png')});await mobileContext.close();report.checks.push('mobile390px: no horizontaloverflow, touch views and tap-to-place table');
 assert.deepEqual(report.errors,[]);report.status='passed';
 }catch(error){report.status='failed';report.failure=error.stack;process.exitCode=1;}finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}})();
