// Independent WebGL viewer. All geometry is local east/north/up in metres.
const $=id=>document.getElementById(id),canvas=$('scene'),gl=canvas.getContext('webgl',{antialias:true});
const add=(a,b)=>a.map((v,i)=>v+b[i]),sub=(a,b)=>a.map((v,i)=>v-b[i]),mul=(a,s)=>a.map(v=>v*s),dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm=a=>mul(a,1/(Math.hypot(...a)||1)),lerp=(a,b,t)=>add(a,mul(sub(b,a),t)),clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
let settings={height:1.5,tilt:20,tables:12,columns:8,rows:2,moduleWidth:1.2,moduleLength:2.4},mode='orbit',origin=null,routeIndex=0,distance=0,extent=60,center=[0,0,0],yaw=-.7,pitch=.65,radius=90,eye=[0,-10,1.7],heading=0,lookPitch=0,drag=null,dirty=true,lastTime=0;
const keys=new Set(),colors={panel:[.7,.79,.88],structure:[.3,.41,.53],grid:[.09,.17,.25],cable:[.2,.45,.62],selected:[.55,.88,1],props:[.48,.58,.65]};
let vertices=[],buffer,program,vertexCount=0;
let plantMode=false,inverterMode=false,acMode=false,dcInitialised=false,stationMode=false;
const stationInverters=[],stationTransformers=[[155,320,1.5],[155,345,1.5]];
function plantInventory(){const modules=Math.ceil(100e6/660);return {targetDCMWp:100,moduleW:660,modules,actualDCMWp:modules*660/1e6,stationCount:10,transformerCount:20,transformerMVA:5,aggregateTransformerMVA:100,illustrative:true,blocks:Array.from({length:10},(_,i)=>({id:i+1,modules:Math.floor(modules/10)+(i<modules%10?1:0),station:{id:i+1,transformers:[{id:2*i+1,mva:5},{id:2*i+2,mva:5}]}}))};}
function plantTablePosition(n){const perBlock=Math.ceil(settings.tables/10),b=Math.min(9,Math.floor(n/perBlock)),local=n%perBlock;return [(b%5)*300+15+(local%5)*45,Math.floor(b/5)*300+20+Math.floor(local/5)*70];}
function buildPlant(){const s=settings,t=s.tilt*Math.PI/180,run=s.rows*(s.moduleLength+.02)-.02,depth=run*Math.cos(t),span=s.columns*(s.moduleWidth+.02)-.02;extent=1500;center=[725,275,0];for(let x=0;x<=1500;x+=50)line([x,0,0],[x,600,0],colors.grid);for(let y=0;y<=600;y+=50)line([0,y,0],[1500,y,0],colors.grid);
 for(let b=0;b<10;b++){const x=(b%5)*300,y=Math.floor(b/5)*300;loop([[x,y,0],[x+250,y,0],[x+250,y+250,0],[x,y+250,0]],colors.structure);loop([[x+110,y+260,0],[x+140,y+260,0],[x+140,y+280,0],[x+110,y+280,0]],colors.selected);box(x+115,y+265,0,6,4,3,colors.panel);box(x+129,y+265,0,6,4,3,colors.panel);}
 for(let n=0;n<s.tables;n++){const [x,y]=plantTablePosition(n);for(const wing of [-1,1])for(let r=0;r<s.rows;r++)for(let c=0;c<s.columns;c++){const v=r*(s.moduleLength+.02),u=c*(s.moduleWidth+.02),p=(dv,du)=>[x+wing*(depth-(v+dv)*Math.cos(t)),y+u+du,s.height+(v+dv)*Math.sin(t)];loop([p(0,0),p(s.moduleLength,0),p(s.moduleLength,s.moduleWidth),p(0,s.moduleWidth)],colors.panel);}for(const yy of [y,y+span])for(const xx of [x-depth,x,x+depth])line([xx,yy,0],[xx,yy,xx===x?s.height+run*Math.sin(t):s.height],colors.structure);}
}
function activatePlant(){plantMode=true;settings={height:1.2,tilt:10,tables:100,columns:10,rows:5,moduleWidth:1.303,moduleLength:2.384};for(const [key,value]of Object.entries(settings)){const el=$('parameters').elements?.[key];if(el)el.value=value;}routes=validateRoutes(Array.from({length:10},(_,b)=>{const x=(b%5)*300,y=Math.floor(b/5)*300;return {id:'BLOCK-'+(b+1),label:'Illustrative block '+(b+1)+' collection route; voltage unspecified',points:[[x+125,y+125,.4],[x+125,y+245,.4],[x+125,y+270,.4]]};}));routeIndex=0;distance=0;populateRoutes();build();fullBlueprint();}
let routes=validateRoutes([
 {id:'DC-01',label:'Array → inverter · DC · voltage unspecified',points:[[0,0,.4],[0,-3,.4],[12,-3,.4],[12,-8,.4],[18,-8,.4]]},
 {id:'AC-01',label:'Inverter → transformer · AC · voltage unspecified',points:[[18,-8,.4],[21,-8,.4],[21,-16,.4],[30,-16,.4]]},
 {id:'EXPORT-01',label:'Transformer → illustrative boundary · voltage unspecified',points:[[30,-16,.4],[35,-16,.4],[35,12,.4],[44,12,.4]]}
]);
function validateRoutes(input){if(!Array.isArray(input)||!input.length||input.length>10000)throw Error('Provide 1–1000 cable routes');let totalPoints=0;const ids=new Set();return input.map(r=>{if(!r||typeof r.id!=='string'||ids.has(r.id)||!Array.isArray(r.points)||r.points.length<2||r.points.length>10000)throw Error('Each cable needs a unique ID and 2–10000 points');totalPoints+=r.points.length;if(totalPoints>100000)throw Error('Maximum 100000 cable points per scene');ids.add(r.id);const points=r.points.map(p=>{if(!Array.isArray(p)||p.length!==3||!p.every(n=>Number.isFinite(n)&&Math.abs(n)<1e7))throw Error('Cable points must be finite metric XYZ coordinates');return [...p];});const lengths=[0];for(let i=1;i<points.length;i++){const segment=Math.hypot(...sub(points[i],points[i-1]));if(segment<1e-6)throw Error('Cable has repeated consecutive points');lengths.push(lengths.at(-1)+segment);}return {id:r.id,label:String(r.label??r.circuit??r.id),points,lengths,length:lengths.at(-1)};});}
function routeAt(r,d){d=clamp(d,0,r.length);let i=1;while(i<r.lengths.length-1&&r.lengths[i]<d)i++;return lerp(r.points[i-1],r.points[i],(d-r.lengths[i-1])/(r.lengths[i]-r.lengths[i-1]));}
function line(a,b,color){vertices.push(...a,...color,...b,...color);}
function loop(points,c){points.forEach((p,i)=>line(p,points[(i+1)%points.length],c));}
function box(x,y,z,w,d,h,c){const p=[[x,y,z],[x+w,y,z],[x+w,y+d,z],[x,y+d,z]];loop(p,c);loop(p.map(a=>add(a,[0,0,h])),c);p.forEach(a=>line(a,add(a,[0,0,h]),c));}
function build(){vertices=[];const s=settings,w=s.moduleWidth,l=s.moduleLength,gap=.02,span=s.columns*(w+gap)-gap,run=s.rows*(l+gap)-gap,t=s.tilt*Math.PI/180,depth=run*Math.cos(t),rise=run*Math.sin(t),across=Math.ceil(Math.sqrt(s.tables));extent=Math.max(60,across*(span+5),Math.ceil(s.tables/across)*(depth+6));center=[(across-1)*(span+5)/2,(Math.ceil(s.tables/across)-1)*(depth+6)/2,0];$('arrayNumber').max=s.tables;
 if(acMode){buildACStation();}else if(inverterMode){buildInverterBlock();}else if(plantMode){buildPlant();}else{
 for(let x=-20;x<=extent+20;x+=5)line([x,-25,0],[x,extent+20,0],colors.grid);for(let y=-25;y<=extent+20;y+=5)line([-20,y,0],[extent+20,y,0],colors.grid);
 for(let n=0;n<s.tables;n++){const ox=(n%across)*(span+5),oy=Math.floor(n/across)*(depth+6);for(let r=0;r<s.rows;r++)for(let c=0;c<s.columns;c++){const x=ox+c*(w+gap),v=r*(l+gap),pt=(dx,dv)=>[x+dx,oy+(v+dv)*Math.cos(t),s.height+(v+dv)*Math.sin(t)];loop([pt(0,0),pt(w,0),pt(w,l),pt(0,l)],colors.panel);}for(const x of [ox,ox+span/2,ox+span]){line([x,oy,0],[x,oy,s.height],colors.structure);line([x,oy+depth,0],[x,oy+depth,s.height+rise],colors.structure);line([x,oy,s.height],[x,oy+depth,s.height+rise],colors.structure);}line([ox,oy,s.height],[ox+span,oy,s.height],colors.structure);line([ox,oy+depth,s.height+rise],[ox+span,oy+depth,s.height+rise],colors.structure);}
 box(17,-9,0,2,2,2,colors.props);box(29,-17,0,3,2,2.5,colors.props);}
 if($('props').checked){box(-5,-4,0,.5,.35,1.75,colors.props);box(-10,-7,0,4.5,1.8,1.6,colors.props);for(let z=0;z<=1;z+=1){const p=Array.from({length:24},(_,i)=>[-3+.6*Math.cos(i*Math.PI/12),-8+.6*Math.sin(i*Math.PI/12),z]);loop(p,colors.props);if(z===0)p.filter((_,i)=>i%6===0).forEach(a=>line(a,add(a,[0,0,1]),colors.props));}}
 routes.forEach((r,i)=>{for(let p=1;p<r.points.length;p++)line(r.points[p-1],r.points[p],i===routeIndex?colors.selected:colors.cable);for(const point of [r.points[0],r.points.at(-1)]){line(add(point,[-.4,0,0]),add(point,[.4,0,0]),colors.selected);line(add(point,[0,-.4,0]),add(point,[0,.4,0]),colors.selected);}});
 if(gl&&buffer){gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,(vertices.length+routes.length*12)*4,gl.DYNAMIC_DRAW);gl.bufferSubData(gl.ARRAY_BUFFER,0,new Float32Array(vertices));vertexCount=vertices.length/6;}
 $('summary').textContent=`${s.tables*s.rows*s.columns} panels · each ${w.toFixed(2)} × ${l.toFixed(2)} m · lower ${s.height.toFixed(2)} m / upper ${(s.height+rise).toFixed(2)} m · 5 m grid · ${routes.length} modelled cables`;
 if(plantMode)$('summary').textContent=`100 MWp DC target · 151,516 × 660 W allocated = 100.00056 MWp · 10 blocks / 10 stations / 20 × 5 MVA transformers = 100 MVA AC nameplate · ${s.tables} representative EW tables (${s.tables*s.rows*s.columns*2} panels drawn), not full module layout · 50 m grid`;
 dirty=true;
}
function matrixMultiply(a,b){const out=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)out[c*4+r]+=a[k*4+r]*b[c*4+k];return out;}
function viewMatrix(position,target,up=[0,0,1]){const z=norm(sub(position,target));if(Math.abs(dot(up,z))>.999)up=[0,1,0];const x=norm(cross(up,z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,position),-dot(y,position),-dot(z,position),1]);}
function projection(aspect,orthographic){const far=Math.max(5000,radius*2+extent*10);if(orthographic){const h=radius/2,w=h*aspect;return new Float32Array([1/w,0,0,0,0,1/h,0,0,0,0,-2/(far-.05),0,0,0,-(far+.05)/(far-.05),1]);}const f=1/Math.tan(Math.PI/6),near=.05;return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0]);}
function camera(){if(mode==='top')return {position:add(center,[0,0,radius]),target:center,up:[0,1,0]};if(mode==='orbit')return {position:add(center,[radius*Math.cos(pitch)*Math.sin(yaw),-radius*Math.cos(pitch)*Math.cos(yaw),radius*Math.sin(pitch)]),target:center};if(mode==='cable'){const r=routes[routeIndex],p=routeAt(r,distance),reverse=$('reverse').checked?-1:1,d=clamp(distance+reverse*.5,0,r.length),q=routeAt(r,d);let forward=sub(q,p);if(Math.hypot(...forward)<.001){let i=1;while(i<r.lengths.length-1&&r.lengths[i]<=distance)i++;forward=mul(sub(r.points[i],r.points[i-1]),reverse);}const position=add(p,[0,0,1.7]);return {position,target:add(position,norm(forward))};}return {position:eye,target:add(eye,[Math.sin(heading)*Math.cos(lookPitch),Math.cos(heading)*Math.cos(lookPitch),Math.sin(lookPitch)])};}
function draw(){const d=Math.min(devicePixelRatio||1,2),w=Math.round(canvas.clientWidth*d),h=Math.round(canvas.clientHeight*d);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}gl.viewport(0,0,w,h);gl.clearColor(.012,.027,.055,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const c=camera();gl.uniformMatrix4fv(gl.getUniformLocation(program,'matrix'),false,matrixMultiply(projection(w/h,mode==='top'),viewMatrix(c.position,c.target,c.up)));gl.drawArrays(gl.LINES,0,vertexCount);if(inverterMode){const pulse=[];for(const [i,r] of routes.entries()){const f=(lastTime/6000+i*.037)%1,d=(i%2?1-f:f)*r.length,a=routeAt(r,d),b=routeAt(r,Math.min(r.length,d+.6));pulse.push(...a,...colors.selected,...b,...colors.selected);}gl.bufferSubData(gl.ARRAY_BUFFER,vertices.length*4,new Float32Array(pulse));gl.drawArrays(gl.LINES,vertexCount,pulse.length/6);}dirty=false;}
function routeUI(){const r=routes[routeIndex];$('routeInfo').textContent=r.label+' · illustrative route';$('distance').max=r.length;$('distance').value=distance;$('distanceInfo').textContent=`${distance.toFixed(2)} / ${r.length.toFixed(2)} m · ${r.id}`;dirty=true;}
function populateRoutes(){$('route').replaceChildren(...routes.map((r,i)=>new Option(r.id,i)));routeUI();}
function changeMode(next){mode=next;$('mode').value=next;keys.clear();if(mode==='walk'){eye=[-3,-8,1.7];heading=.3;lookPitch=0;}if(mode==='fly'){eye=[-4,-10,8];heading=.3;lookPitch=-.2;}$('help').textContent=mode==='cable'?'W/S or ↑/↓: travel selected cable · slider: exact distance · select any modelled cable':mode==='walk'||mode==='fly'?'Drag to look · WASD / arrows to move · Shift faster'+(mode==='fly'?' · Q/E down/up':' · eye height 1.7 m; no collision model'):'Drag to '+(mode==='top'?'pan':'orbit')+' · wheel zoom · right-drag pan';dirty=true;}
function reset(){radius=extent*1.8;yaw=-.7;pitch=.65;build();changeMode(mode);}
function fullBlueprint(){build();const points=[];for(let i=0;i<vertices.length;i+=6)points.push([vertices[i],vertices[i+1]]);let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const [x,y] of points){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);}center=[(minX+maxX)/2,(minY+maxY)/2,0];radius=Math.max(maxY-minY,(maxX-minX)/(canvas.clientWidth/canvas.clientHeight))*1.15;document.querySelector('aside').hidden=true;$('show').hidden=false;changeMode('top');canvas.focus();}
function tick(time){const dt=Math.min((time-lastTime)/1000,.05);lastTime=time;const forward=Number(keys.has('w')||keys.has('arrowup'))-Number(keys.has('s')||keys.has('arrowdown')),side=Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft')),speed=clamp(Number($('speed').value)||2,.1,20)*(keys.has('shift')?3:1);if(mode==='cable'&&forward){distance=clamp(distance+forward*speed*dt*($('reverse').checked?-1:1),0,routes[routeIndex].length);routeUI();}if((mode==='walk'||mode==='fly')&&(forward||side||keys.has('q')||keys.has('e'))){const horizontal=forward*(mode==='fly'?Math.cos(lookPitch):1);eye=add(eye,mul([Math.sin(heading)*horizontal+Math.cos(heading)*side,Math.cos(heading)*horizontal-Math.sin(heading)*side,mode==='fly'?Math.sin(lookPitch)*forward+Number(keys.has('e'))-Number(keys.has('q')):0],speed*dt));if(mode==='walk')eye[2]=1.7;dirty=true;}if((dirty||inverterMode)&&gl)draw();requestAnimationFrame(tick);}
function init(){if(!gl)throw Error('WebGL unavailable. Enable browser graphics acceleration to use this viewer.');const shader=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec3 position; attribute vec3 color; varying vec3 tint; uniform mat4 matrix; void main(){tint=color;gl_Position=matrix*vec4(position,1.0);}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,'precision mediump float; varying vec3 tint; void main(){gl_FragColor=vec4(tint,1.0);}'));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);for(const [name,offset] of [['position',0],['color',12]]){const loc=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,3,gl.FLOAT,false,24,offset);}gl.enable(gl.DEPTH_TEST);populateRoutes();build();reset();requestAnimationFrame(tick);}
 $('parameters').onsubmit=e=>{e.preventDefault();try{const next={};for(const key of Object.keys(settings)){const el=e.target.elements[key],v=Number(el.value);if(!el.value||!Number.isFinite(v)||v<Number(el.min)||v>Number(el.max)||(['tables','columns','rows'].includes(key)&&!Number.isInteger(v)))throw Error('Check '+key+' range');next[key]=v;}settings=next;build();$('error').textContent='';}catch(err){$('error').textContent=err.message;}};
 $('props').onchange=build;$('fit').onclick=reset;$('mode').onchange=e=>changeMode(e.target.value);$('route').onchange=e=>{routeIndex=Number(e.target.value);distance=0;build();routeUI();changeMode('cable');};$('distance').oninput=e=>{distance=Number(e.target.value);routeUI();changeMode('cable');};$('start').onclick=()=>{distance=0;routeUI();changeMode('cable');};$('end').onclick=()=>{distance=routes[routeIndex].length;routeUI();changeMode('cable');};$('reverse').onchange=()=>dirty=true;
 $('blueprint').onclick=fullBlueprint;$('focusArray').onclick=()=>{const n=Number($('arrayNumber').value);if(!Number.isInteger(n)||n<1||n>settings.tables){$('error').textContent='Choose array 1–'+settings.tables;return;}const width=settings.columns*(settings.moduleWidth+.02)-.02,depth=(settings.rows*(settings.moduleLength+.02)-.02)*Math.cos(settings.tilt*Math.PI/180),across=Math.ceil(Math.sqrt(settings.tables)),x=((n-1)%across)*(width+5),y=Math.floor((n-1)/across)*(depth+6);changeMode('fly');eye=[x+width/2,y-4,settings.height+2];heading=0;lookPitch=-.2;canvas.focus();$('error').textContent='';};
 $('hide').onclick=()=>{document.querySelector('aside').hidden=true;$('show').hidden=false;canvas.focus();};$('show').onclick=()=>{document.querySelector('aside').hidden=false;$('show').hidden=true;};
 canvas.oncontextmenu=e=>e.preventDefault();canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,button:e.button};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;if(mode==='top'||(mode==='orbit'&&drag.button===2)){const scale=radius/canvas.clientHeight;center[0]-=dx*scale;center[1]+=dy*scale;}else if(mode==='orbit'){yaw-=dx*.006;pitch=clamp(pitch+dy*.006,.03,1.56);}else if(mode==='walk'||mode==='fly'){heading+=dx*.005;lookPitch=clamp(lookPitch-dy*.005,-1.45,1.45);}dirty=true;};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;canvas.addEventListener('wheel',e=>{if(mode==='orbit'||mode==='top'){e.preventDefault();radius=clamp(radius*Math.exp(e.deltaY*.001),2,10000);dirty=true;}else if(mode==='walk'||mode==='fly'){e.preventDefault();const step=-e.deltaY*.015;eye=add(eye,mul([Math.sin(heading)*Math.cos(lookPitch),Math.cos(heading)*Math.cos(lookPitch),mode==='fly'?Math.sin(lookPitch):0],step));dirty=true;}},{passive:false});
 canvas.addEventListener('pointerdown',()=>canvas.focus());$('mode').addEventListener('change',()=>canvas.focus());$('route').addEventListener('change',()=>canvas.focus());for(const id of ['start','end'])$(id).addEventListener('click',()=>canvas.focus());$('distance').addEventListener('change',()=>canvas.focus());
 window.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA|BUTTON/.test(e.target.tagName))return;const k=e.key.toLowerCase();if(['w','a','s','d','q','e','arrowup','arrowdown','arrowleft','arrowright','shift'].includes(k)){e.preventDefault();keys.add(k);}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();drag=null;});window.addEventListener('resize',()=>dirty=true);
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();$('error').textContent='Graphics context lost. Reload this page to restore the scene.';});
 window.electricalExplorer={setOrigin(value){if(!value||!Number.isFinite(value.latitude)||Math.abs(value.latitude)>90||!Number.isFinite(value.longitude)||Math.abs(value.longitude)>180)throw Error('Valid latitude and longitude required');origin={latitude:value.latitude,longitude:value.longitude,label:String(value.label??'Public location')};$('origin').textContent=`${origin.label} · ${origin.latitude.toFixed(6)}, ${origin.longitude.toFixed(6)} · local illustrative scene; cables are not surveyed`;},setRoutes(input){routes=validateRoutes(input);routeIndex=0;distance=0;populateRoutes();build();},get state(){return {settings:{...settings},mode,origin:origin&&{...origin},route:routes[routeIndex].id,distance,routes:routes.map(r=>({id:r.id,label:r.label,length:r.length,points:r.points.map(p=>[...p])})),gpu:!!gl,vertexCount};}};
 $('plantPreset').onclick=activatePlant;
 const standardFocus=$('focusArray').onclick;
 $('focusArray').onclick=()=>{if(!plantMode)return standardFocus();const n=Number($('arrayNumber').value);if(!Number.isInteger(n)||n<1||n>settings.tables){$('error').textContent='Choose representative array 1–'+settings.tables;return;}const [x,y]=plantTablePosition(n-1);changeMode('fly');eye=[x,y-8,settings.height+4];heading=0;lookPitch=-.15;canvas.focus();$('error').textContent='';};
 Object.defineProperty(window.electricalExplorer,'plantInventory',{get:()=>plantMode?plantInventory():null});
 try{init();}catch(err){$('error').textContent=err.message;}

// Full paired table: five portrait rows, three 30-module strings per row per face.
// Topology follows the existing public inverter-48 drawing; routes remain illustrative.
const blockLayout={rowGap:8,aisleGap:10,ridgeGap:.5},tableOffsets=new Map(),inverterPosition=[18,-4,1];
function blockPosition(n){const depth=(settings.rows*(settings.moduleLength+.02)-.02)*Math.cos(settings.tilt*Math.PI/180),span=settings.columns*(settings.moduleWidth+.02)-.02,o=tableOffsets.get(n)||[0,0];return [(n%4)*(2*depth+blockLayout.ridgeGap+blockLayout.rowGap)+o[0],Math.floor(n/4)*(span+blockLayout.aisleGap)+o[1]];}
function blockStrings(){const s=settings,t=s.tilt*Math.PI/180,run=s.rows*(s.moduleLength+.02)-.02,depth=run*Math.cos(t),result=[];for(let n=0;n<s.tables;n++){const [x,y]=blockPosition(n);for(const side of [-1,1])for(let r=0;r<s.rows;r++)for(let group=0;group<Math.ceil(s.columns/30);group++){const modules=[];for(let c=group*30;c<Math.min(s.columns,(group+1)*30);c++){const v=(side===1?s.rows-1-r:r)*(s.moduleLength+.02),u=c*(s.moduleWidth+.02),p=(dv,du)=>[x+side*(blockLayout.ridgeGap/2+depth-(v+dv)*Math.cos(t)),y+u+du,s.height+(v+dv)*Math.sin(t)];modules.push({corners:[p(0,0),p(s.moduleLength,0),p(s.moduleLength,s.moduleWidth),p(0,s.moduleWidth)],terminal:p(s.moduleLength/2,s.moduleWidth/2)});}const index=result.length;result.push({table:n,side,row:r,group,connected:stationMode?index<672:r<4,inverter:stationMode?Math.floor(index/24):0,modules});}}return result;}
function buildInverterBlock(){extent=145;center=[0,59,0];for(let x=-20;x<=30;x+=10)line([x,-15,0],[x,130,0],colors.grid);for(let y=-15;y<=130;y+=10)line([-20,y,0],[30,y,0],colors.grid);for(const string of blockStrings()){for(const m of string.modules)loop(m.corners,string.connected?colors.panel:colors.structure);for(let i=1;i<string.modules.length;i++)line(string.modules[i-1].terminal,string.modules[i].terminal,colors.cable);const ends=[string.modules[0].corners[0],string.modules.at(-1).corners[2]];for(const p of ends)line([p[0],p[1],0],p,colors.structure);}if(stationMode){extent=800;center=[65,360,0];for(const p of stationInverters)box(p[0]-1,p[1]-1,0,2,2,2,colors.selected);for(const p of stationTransformers)box(p[0]-2,p[1]-2,0,4,4,3,colors.selected);for(const p of stationInverters){const ty=stationTransformers[Math.floor(stationInverters.indexOf(p)/14)][1];trench([p[0],p[1]],[140,p[1]],.35);trench([140,p[1]],[140,ty],2.6);trench([140,ty],[155,ty],2.6);}}else box(inverterPosition[0]-1,inverterPosition[1]-1,0,2,2,2,colors.selected);}
function updateBlockRoutes(){routes=validateRoutes(blockStrings().filter(s=>s.connected).flatMap((string,i)=>[0,1].map(end=>{const p=string.modules[end?string.modules.length-1:0].terminal,offset=end*.15,destination=stationMode?stationInverters[string.inverter]:inverterPosition,lane=stationMode?destination[1]-2:-8;return {id:`S${String(i+1).padStart(2,'0')}-${end?'NEG':'POS'}`,label:`String ${i+1} ${end?'negative':'positive'} to inverter ${string.inverter+1}; assumed DC route`,points:[p,[p[0],p[1],.4],[p[0],lane-offset,.4],[destination[0]+offset,lane-offset,.4],[destination[0]+offset,destination[1],1]].filter((q,j,all)=>!j||Math.hypot(...sub(q,all[j-1]))>1e-8)};})));if(stationMode)routes=validateRoutes([...routes,...stationACPaths()]);routeIndex=0;distance=0;populateRoutes();}
function activateInverterBlock(){if(stationMode){dcInitialised=false;stationMode=false;tableOffsets.clear();}acMode=false;inverterMode=true;plantMode=false;if(!dcInitialised){settings={height:1.2,tilt:10,tables:1,columns:90,rows:5,moduleWidth:1.303,moduleLength:2.384};dcInitialised=true;}for(const[key,value]of Object.entries(settings)){const el=$('parameters').elements?.[key];if(el)el.value=value;}updateBlockRoutes();build();radius=165;changeMode('orbit');yaw=-.65;pitch=.85;document.querySelector('aside').hidden=true;$('show').hidden=false;canvas.focus();}
const originalBuild=build;
build=function(){originalBuild();if(inverterMode){const all=blockStrings(),connected=all.filter(s=>s.connected);$('summary').textContent=`${settings.tables} paired table(s) | ${all.length} strings / ${all.reduce((n,s)=>n+s.modules.length,0)} modules drawn | ${connected.length} connected strings / ${connected.length*2} DC home cables | ${all.length-connected.length} strings assigned elsewhere | ${stationMode?"28 inverters / 2 x 5 MVA / 84 AC phase cables | ":""}illustrative cable flow`;}};
const originalSubmit=$('parameters').onsubmit;
$('parameters').onsubmit=e=>{originalSubmit(e);if(inverterMode&&!$('error').textContent){updateBlockRoutes();build();}};
const plantClick=$('plantPreset').onclick;$('plantPreset').onclick=()=>{stationMode=false;dcInitialised=false;acMode=false;inverterMode=false;plantClick();};
Object.assign(window.electricalExplorer,{startInverter:activateInverterBlock,setView(next){changeMode(next);if(inverterMode&&(next==='walk'||next==='fly')){eye=[-16,-4,next==='fly'?8:1.7];heading=0;lookPitch=next==='fly'?-.2:.05;}canvas.focus();},blueprint:fullBlueprint,project(point){const c=camera(),m=matrixMultiply(projection(canvas.clientWidth/canvas.clientHeight,mode==='top'),viewMatrix(c.position,c.target,c.up)),v=[...point,1],p=[0,0,0,0];for(let r=0;r<4;r++)for(let k=0;k<4;k++)p[r]+=m[k*4+r]*v[k];if(p[3]<=0||p[2]/p[3]>1)return null;return [(p[0]/p[3]+1)*canvas.clientWidth/2,(1-p[1]/p[3])*canvas.clientHeight/2];},getPickTargets(){return inverterMode?[...Array.from({length:settings.tables},(_,n)=>{const[x,y]=blockPosition(n);return {kind:'table',id:n+1,point:[x,y+3,settings.height+1]};}),...(stationMode?stationInverters.map((p,i)=>({kind:'inverter',id:i+1,point:[...p]})):[{kind:'inverter',id:1,point:[...inverterPosition]}])]:[];},blockInventory(){return inverterMode?{modulesPerString:Math.min(30,settings.columns),strings:blockStrings().filter(s=>s.connected).length,totalStrings:blockStrings().length,spareStrings:blockStrings().filter(s=>!s.connected).length,connectedModules:blockStrings().filter(s=>s.connected).reduce((n,s)=>n+s.modules.length,0),dcHomeCables:blockStrings().filter(s=>s.connected).length*2,modules:settings.tables*settings.rows*settings.columns*2,seriesLinks:blockStrings().filter(s=>s.connected).reduce((n,s)=>n+s.modules.length-1,0),stations:stationMode?1:10,invertersPerStation:28,transformersPerStation:2,transformerMVA:5}:null;}});

Object.assign(window.electricalExplorer,{setSpacing(gap){if(!Number.isFinite(gap)||gap<0||gap>100)throw Error('Row gap 0?100 m');blockLayout.rowGap=gap;updateBlockRoutes();build();},moveTable(id,dx,dy){if(!inverterMode||mode!=='top')return;const old=tableOffsets.get(id-1)||[0,0],scale=radius/canvas.clientHeight;tableOffsets.set(id-1,[old[0]+dx*scale,old[1]-dy*scale]);updateBlockRoutes();build();},getSpacing(){return blockLayout.rowGap;}});

window.electricalExplorer.placeTable=(px,py)=>{if(!inverterMode||mode!=='top')return;if(settings.tables>=100)throw Error('This prototype currently displays up to 100 complete tables.');const x=center[0]+(px-canvas.clientWidth/2)*radius/canvas.clientHeight,y=center[1]-(py-canvas.clientHeight/2)*radius/canvas.clientHeight,n=settings.tables,[ox,oy]=blockPosition(n);tableOffsets.set(n,[x-ox,y-oy]);settings.tables++;$('parameters').elements.tables.value=settings.tables;updateBlockRoutes();build();};

window.electricalExplorer.moveInverter=(dx,dy,id=1)=>{if(!inverterMode||mode!=='top')return;const scale=radius/canvas.clientHeight;const position=stationMode?stationInverters[id-1]:inverterPosition;position[0]+=dx*scale;position[1]-=dy*scale;const keepCenter=[...center];updateBlockRoutes();build();center=keepCenter;};

const acLayout={depth:.9,formation:'trefoil',diameter:.0374,inverters:Array.from({length:28},(_,i)=>({id:i+1,section:Math.floor(i/14),point:[(i%7)*10,Math.floor(i/14)===0?Math.floor((i%14)/7)*15:85+Math.floor((i%14)/7)*15,1]})),transformers:[{id:1,point:[90,43,1.5]},{id:2,point:[90,57,1.5]}]};
function acPaths(){const z=-acLayout.depth+.05+acLayout.diameter/2,d=acLayout.diameter;return acLayout.inverters.flatMap(inv=>{const [x,y]=inv.point,[tx,ty]=acLayout.transformers[inv.section].point,collection=inv.section===0?30:70;return [0,1,2].map(phase=>{const offset=acLayout.formation==='flat'?(phase-1)*d:phase===0?-d/2:phase===1?d/2:0,pz=z+(acLayout.formation==='trefoil'&&phase===2?Math.sqrt(3)*d/2:0);return {id:`INV-${inv.id}-L${phase+1}`,label:`Inverter ${inv.id} to transformer ${inv.section+1}; 400 mm2 Al; 800 V; assumed route`,points:[[x+offset,y,1],[x+offset,y,pz],[x+offset,collection,pz],[tx+offset,collection,pz],[tx+offset,ty,pz],[tx+offset,ty,1]].filter((p,i,all)=>!i||Math.hypot(...sub(p,all[i-1]))>1e-8)};});});}
function trench(a,b,width){const dx=b[0]-a[0],dy=b[1]-a[1],l=Math.hypot(dx,dy);if(l<1e-8)return;const ox=-dy/l*width/2,oy=dx/l*width/2;for(const z of [0,-acLayout.depth])loop([[a[0]+ox,a[1]+oy,z],[b[0]+ox,b[1]+oy,z],[b[0]-ox,b[1]-oy,z],[a[0]-ox,a[1]-oy,z]],colors.structure);for(const p of [a,b])for(const sign of [-1,1])line([p[0]+sign*ox,p[1]+sign*oy,0],[p[0]+sign*ox,p[1]+sign*oy,-acLayout.depth],colors.grid);}
function buildACStation(){extent=130;center=[45,50,0];for(let x=-10;x<=110;x+=10)line([x,-10,0],[x,110,0],colors.grid);for(let y=-10;y<=110;y+=10)line([-10,y,0],[110,y,0],colors.grid);for(const inv of acLayout.inverters){const[x,y]=inv.point,cy=inv.section===0?30:70;box(x-1,y-.5,0,2,1,2,colors.panel);trench([x,y],[x,cy],.35);}for(let section=0;section<2;section++){const[tx,ty]=acLayout.transformers[section].point,cy=section===0?30:70;trench([0,cy],[tx,cy],2.6);trench([tx,cy],[tx,ty],2.6);box(tx-2,ty-1.5,0,4,3,3,colors.selected);}loop([[82,35,0],[99,35,0],[99,65,0],[82,65,0]],colors.props);}
function refreshAC(){routes=validateRoutes(acPaths());routeIndex=Math.min(routeIndex,routes.length-1);distance=0;populateRoutes();const keepCenter=[...center];build();center=keepCenter;$('summary').textContent=`One 10 MVA station | 2 x 5 MVA transformers | ${acLayout.inverters.length} x 352 kVA inverters | ${acLayout.inverters.length*3} x 400 mm2 AC phase cables | ${acLayout.formation} | trench depth ${acLayout.depth.toFixed(2)} m | illustrative routes, not surveyed`;$('help').textContent='Drag to orbit; Blueprint for top view; click equipment to move it. Transparent trench outlines show depth. 352 kVA at 800 V; no isolators modelled.';}
function startAC(){if(stationMode)dcInitialised=false;stationMode=false;inverterMode=false;plantMode=false;acMode=true;refreshAC();radius=190;center=[45,50,0];yaw=-.6;pitch=.75;changeMode('orbit');document.querySelector('aside').hidden=true;$('show').hidden=false;canvas.focus();}
const defaultPickTargets=window.electricalExplorer.getPickTargets;
Object.assign(window.electricalExplorer,{startAC,getPickTargets(){return acMode?[...acLayout.inverters.map(n=>({kind:'ac-inverter',id:n.id,point:[...n.point]})),...acLayout.transformers.map(n=>({kind:'transformer',id:n.id,point:[...n.point]}))]:defaultPickTargets();},setTrench(depth,formation){if(!Number.isFinite(depth)||depth<.2||depth>5||!['flat','trefoil'].includes(formation))throw Error('Depth0.2–5 m; flat or trefoil');acLayout.depth=depth;acLayout.formation=formation;if(acMode)refreshAC();},getTrench(){return {depth:acLayout.depth,formation:acLayout.formation};},moveAC(kind,id,dx,dy){if(!acMode||mode!=='top')return;const item=(kind==='transformer'?acLayout.transformers:acLayout.inverters).find(n=>n.id===id);if(!item)return;const scale=radius/canvas.clientHeight;item.point[0]+=dx*scale;item.point[1]-=dy*scale;refreshAC();},acInventory(){return acMode?{inverters:acLayout.inverters.length,transformers:2,transformerMVA:5,phaseCables:acLayout.inverters.length*3,areaMm2:400,kvaPerInverter:352,trenchDepth:acLayout.depth}:null;}});

Object.assign(window.electricalExplorer,{getRidgeGap(){return blockLayout.ridgeGap;},setRidgeGap(gap){if(!Number.isFinite(gap)||gap<0||gap>20)throw Error('Ridge gap must be between 0 and20m');blockLayout.ridgeGap=gap;updateBlockRoutes();build();}});

Object.assign(window.electricalExplorer,{acSection(id){return acLayout.inverters.find(n=>n.id===id)?.section??0;},acSectionCount(section){return acLayout.inverters.filter(n=>n.section===section).length;},setACSectionCount(section,count){if(![0,1].includes(section)||!Number.isInteger(count)||count<1||count>100)throw Error('1 to100 inverters per section in this prototype');let current=acLayout.inverters.filter(n=>n.section===section);while(current.length>count){const removed=current.pop();acLayout.inverters=acLayout.inverters.filter(n=>n.id!==removed.id);}while(current.length<count){const n=current.length,id=Math.max(...acLayout.inverters.map(n=>n.id))+1,item={id,section,point:[(n%7)*10,section===0?-Math.floor(n/7)*15:85+Math.floor(n/7)*15,1]};acLayout.inverters.push(item);current.push(item);}if(acMode)refreshAC();}});

// Generic complete station: 28 x 24 strings; surplus table strings remain unassigned.
function stationACPaths(){return stationInverters.flatMap((p,i)=>[0,1,2].map(phase=>{const t=stationTransformers[Math.floor(i/14)],o=acLayout.formation==='flat'?(phase-1)*.0374:phase===0?-.0187:phase===1?.0187:0,z=-acLayout.depth+.05+.0374/2+(acLayout.formation==='trefoil'&&phase===2?Math.sqrt(3)*.0374/2:0);return {id:`ST-INV-${i+1}-L${phase+1}`,label:`Inverter ${i+1} to transformer ${Math.floor(i/14)+1}; 400 mm2 Al; 800 V; illustrative`,points:[[p[0]+o,p[1],1],[p[0]+o,p[1],z],[140+o,p[1],z],[140+o,t[1],z],[t[0]+o,t[1],z],[t[0]+o,t[1],1]].filter((q,j,a)=>!j||Math.hypot(...sub(q,a[j-1]))>1e-8)};}));}
function startStation(){stationMode=true;inverterMode=true;acMode=false;plantMode=false;dcInitialised=true;tableOffsets.clear();settings={height:1.2,tilt:10,tables:23,columns:90,rows:5,moduleWidth:1.303,moduleLength:2.384};stationInverters.length=0;for(let i=0;i<28;i++){const table=Math.floor(i*24/30),[x,y]=blockPosition(table);stationInverters.push([x+15,y+10+(i*24%30)*3,1]);}for(const [key,value]of Object.entries(settings)){const el=$('parameters').elements?.[key];if(el)el.value=value;}updateBlockRoutes();build();radius=850;changeMode('orbit');yaw=-.35;pitch=.95;document.querySelector('aside').hidden=true;$('show').hidden=false;canvas.focus();}
Object.assign(window.electricalExplorer,{startStation,stationInventory(){if(!stationMode)return null;const strings=blockStrings(),connected=strings.filter(s=>s.connected);return {tables:settings.tables,installedModules:strings.reduce((n,s)=>n+s.modules.length,0),connectedModules:connected.reduce((n,s)=>n+s.modules.length,0),connectedStrings:connected.length,spareStrings:strings.length-connected.length,inverters:28,stringsPerInverter:stationInverters.map((_,i)=>connected.filter(s=>s.inverter===i).length),dcHomeCables:connected.length*2,acPhaseCables:84,transformers:2,transformerMVA:5,inverterKVA:352,aggregateInverterMVA:28*352/1000};}});

window.electricalExplorer.zoom=factor=>{if(!Number.isFinite(factor)||factor<=0)return;if(mode==='walk'||mode==='fly'){const step=(1-factor)*12;eye=add(eye,mul([Math.sin(heading)*Math.cos(lookPitch),Math.cos(heading)*Math.cos(lookPitch),mode==='fly'?Math.sin(lookPitch):0],step));}else radius=clamp(radius*factor,2,10000);dirty=true;};
