const api=window.electricalExplorer,canvas=document.getElementById('scene');
const bar=document.createElement('nav');bar.style.cssText='position:fixed;right:14px;top:14px;display:flex;gap:6px;z-index:2';bar.innerHTML='<button data-view="walk">Walk</button><button data-view="fly">Fly</button><button id="direct-top">Blueprint</button><button id="place-table">Add table</button><a href="https://globalgrid2050.com/ventus/wiring/inverter-station.html" style="padding:7px;background:#0d2035;color:#b7d9ef">10-station wiring</a>';document.body.append(bar);for(const b of bar.querySelectorAll('[data-view]'))b.onclick=()=>api.setView(b.dataset.view);bar.querySelector('#direct-top').onclick=()=>api.blueprint();
const edit=document.createElement('section');edit.id='direct-edit';edit.hidden=true;edit.style.cssText='position:fixed;right:14px;top:60px;padding:12px;background:#081424f5;border:1px solid #496078;z-index:3;max-width:300px';document.body.append(edit);
function inspect(target){edit.hidden=false;if(target.kind==='inverter'){edit.innerHTML='<strong>One inverter</strong><p>24 strings × 30 modules<br>48 DC home cables</p><p><a style="color:#b7d9ef" href="https://globalgrid2050.com/ventus/wiring/inverter-48.html">Open complete wiring</a></p><button id="close-direct">Close</button>';}else{const s=api.state.settings;edit.innerHTML=`<strong>Table ${target.id} · two 30-module faces</strong><label>Lower edge m <input id="direct-height" type="number" min=".1" max="20" step=".1" value="${s.height}"></label><label>Tilt ° <input id="direct-tilt" type="number" min="0" max="60" step="1" value="${s.tilt}"></label><label>Clear row gap m <input id="direct-gap" type="number" min="0" max="100" step=".5" value="${api.getSpacing()}"></label><p>Height, tilt and spacing apply to repeated tables. Geometry only; routes are illustrative.</p><button id="direct-move">Move this table</button><button id="direct-apply">Apply</button> <button id="close-direct">Close</button>`;document.getElementById('direct-move').onclick=()=>{moveTarget=target;api.blueprint();edit.hidden=true;};document.getElementById('direct-apply').onclick=()=>{const form=document.getElementById('parameters');form.elements.height.value=document.getElementById('direct-height').value;form.elements.tilt.value=document.getElementById('direct-tilt').value;form.requestSubmit();api.setSpacing(Number(document.getElementById('direct-gap').value));};}document.getElementById('close-direct').onclick=()=>{edit.hidden=true;canvas.focus();};}
let down,moveTarget=null,placing=false;document.getElementById("place-table").onclick=()=>{placing=true;api.blueprint();};canvas.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);canvas.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;if(placing){placing=false;try{api.placeTable(e.clientX,e.clientY);}catch(error){document.getElementById('error').textContent=error.message;document.getElementById('show').click();}return;}let best=null,distance=65;for(const target of api.getPickTargets()){const p=api.project(target.point);if(!p)continue;const d=Math.hypot(p[0]-e.clientX,p[1]-e.clientY);if(d<distance){distance=d;best=target;}}if(best)inspect(best);});
// Test harness may explicitly load the legacy baseline; users start in the complete block.
if(!new URLSearchParams(location.search).has('baseline'))api.startInverter();

canvas.addEventListener('pointerdown',e=>{if(!moveTarget)return;down=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);e.stopImmediatePropagation();},true);
canvas.addEventListener('pointermove',e=>{if(!moveTarget||!down||!e.buttons)return;api.moveTable(moveTarget.id,e.clientX-down[0],e.clientY-down[1]);down=[e.clientX,e.clientY];e.stopImmediatePropagation();},true);
canvas.addEventListener('pointerup',e=>{if(moveTarget){moveTarget=null;down=null;e.stopImmediatePropagation();}},true);
